on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "5793266"
          username: "Dashxboard Releases"
          avatar_url: "https://cdn.discordapp.com/avatars/1320529387526951055/8525231358b5ebf0454070b8e06044ed.png"
          footer_title: "@dashxboard-web"
          footer_icon_url: "https://cdn.discordapp.com/avatars/1320529387526951055/8525231358b5ebf0454070b8e06044ed.png"
          footer_timestamp: true
          max_description: "4096"
          reduce_headings: true
